DROP TABLE SALE;	


CREATE TABLE SALE(
	SaleId int IDENTITY (1,1) PRIMARY KEY,
	Date datetime NOT NULL,
	Price decimal NOT NULL,
	IsSetteled bit NOT NULL DEFAULT 0
	ItemId int FOREIGN KEY REFERENCES ITEM(ItemId)
);
